### ISSUE TITLE
App not building due to Double-quoted include in framework header 

### ISSUE THREAD

**Issue by JavierSilvaFreeNow** [AppsFlyerSDK/AppsFlyerFramework#155] opened 2021-01-21 08:01 UTC
# Report

## SDK Version

6.1.4

## What did you do?

Migrated the framework from Cocoapods to SPM

## What did you expect to happen?

App to build successfully

## What happened instead?

App fails to build due to "Double-quoted include" warning in AppsFlyerLib.h and AppsFlyerShareInviteHelper.h

## Please provide any other relevant information.

We have the "Treat Warnings as Errors" setting enabled to prevent warnings from being unattended on our project. Unfortunately this also means that the warnings caused by the library are also treated as errors, which makes the build process fail.

**Comment by rlziii** [comment] 2021-10-11 20:53
Any information or progress on this issue?

**Comment by SeanMcTex** [comment] 2021-11-23 20:09
Would also like to see a fix for this. (Also, hi @rlziii !)

**Comment by rlziii** [comment] 2021-11-23 20:14
Can confirm that we are still seeing these warnings on the latest version of Xcode (13.1).

(👋 @SeanMcTex 👋)

**Comment by mathaeus** [comment] 2022-01-04 13:08
Also getting those warnings for a long time already and would really appreciate if they could get fixed @andr-ggn.
We are on `6.5.0`.

**Comment by leearmstrong** [comment] 2022-05-06 14:13
Any chance these could be fixed?

**Comment by leearmstrong** [comment] 2022-08-17 09:06
Any update?

**Comment by af-fess** [comment] 2022-08-18 13:37
The fix will come with v6.9.0 (next release)

**Comment by af-fess** [comment] 2023-01-05 09:24
Possible duplicate of https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/203

**Closed** 2023-01-05 09:24 UTC
