### ISSUE TITLE
Apple M1 arm64-simulator support

### ISSUE THREAD

**Issue by quentinfasquel** [AppsFlyerSDK/AppsFlyerFramework#150] opened 2020-12-22 10:30 UTC
# Report

## SDK Version
6.1.2

## What did you do?
Integrating AppsFlyer with Swift Package Manager

## What did you expect to happen?
Run AppsFlyer on simulator

## What happened instead?
Missing architecture arm64-simulator

## Please provide any other relevant information.
I am working on most recent's Apple MacBook Pro (processor Apple M1)

**Comment by af-fess** [comment] 2020-12-29 16:19
We work on it. 
I will give you more information once I get more updates.

**Comment by bettola** [comment] 2021-01-14 10:08
any update on this one??

**Comment by davidhodge** [comment] 2021-01-15 02:23
Would love to see a fix for this. Thanks!

**Comment by alextudge** [comment] 2021-01-15 10:18
Also experiencing this - unable to compile for iOS14 simulators with M1. With a lot of stripping and scripts I can get it to work for < iOS14 but not ideal!

**Comment by af-obodovskyi** [comment] 2021-01-15 11:25
@bettola , @davidhodge We are working on it to provide the solution as soon as possible. 
Could you provide us with following information? 

- Your Xcode version
- **Go to Project > Build settings** and search for **Architectures** and **Excluded architectures** and provide us the information for those fields. 

**Possible solution, untill we add arm64 support to AppsFlyerLib:**
Try to add arm64 to excluded architectures for iOS simulator in your project settings.

**Comment by alextudge** [comment] 2021-01-15 14:47
Unfortunately that causes a lot of issues with all other packages

**Comment by gilbertCardioCast** [comment] 2021-01-19 15:47
Running Xcode through Rosetta lets you build. Albeit not ideal but an easy work around.

**Comment by vmvinoth** [comment] 2021-01-21 07:08
> Running Xcode through Rosetta lets you build. Albeit not ideal but an easy work around.

This Works!!!

1 - With Xcode closed (Important) Go to finder -> Applications
2 - Right Click on Xcode and select "Get Info"
3 - On the info panel check "Open using Rosetta"
4 - Open Xcode again and build
5 - It WORKS

**Comment by misolubarda** [comment] 2021-01-21 14:00
Just a question with a kind intention... What is the priority of fixing this issue? I wonder only because this is the last constraint I have in my project to let Xcode run without Rosetta support.

**Comment by shakked** [comment] 2021-01-21 14:45
This is ridiculous. M1 has been released for months and AppsFlyer can't fix this issue? Literally the only SDK that doesn't work. Get it together.

**Comment by gilbertCardioCast** [comment] 2021-01-28 14:40
Can we get a status on this please? @af-fess @af-obodovskyi

**Comment by nesfahani** [comment] 2021-02-03 00:18
when are you losers going to update this

**Comment by af-fess** [comment] 2021-02-04 07:26
To support arm64 simulator,  any binary should be built with Xcode 12.

The min ios version will be change from 8 to 9.
Clients using Xcode 11 will not be able to use a new AppsFlyer SDK version.

**Comment by davidhodge** [comment] 2021-02-12 06:35
There's always this option: https://bogo.wtf/arm64-to-sim.html

**Comment by heps** [comment] 2021-02-15 19:52
> There's always this option: https://bogo.wtf/arm64-to-sim.html

Confirmed. I've just used the tutorial and successfully made current version working.
Recommended.

**Comment by navartis** [comment] 2021-02-17 14:02
> To support arm64 simulator, any binary should be built with Xcode 12.
> 
> The min ios version will be changed from 8 to 9.
> Clients using Xcode 11 will not be able to use a new AppsFlyer SDK version.
> 
> We expect to release M1 support at the end of Feb.

It seems to me that a few hours will be enough to rebuild the library using one of the Mac rental services. 

For example https://www.macstadium.com (not advertising)

**Comment by Nekitosss** [comment] 2021-03-01 09:45
Guys, any updates here? Its march already

**Comment by navartis** [comment] 2021-03-01 12:46
Just checked latest 6.2.2 release that happened 11 days a go.

Still does not support....

**Comment by navartis** [comment] 2021-03-03 12:05
@af-fess How about good news for us?;)

**Comment by appsfcker** [comment] 2021-03-04 03:32
appsflyer received $210M in funding last year and its taking months just to rebuild your SDK with the newest Xcode?

**Comment by af-fess** [comment] 2021-03-07 15:18
We still work on it. We expect M1 support in v6.3.0.

**Comment by atrinh0** [comment] 2021-03-29 11:11
@af-fess Hi Maxim, any updates or ETA on when we can expect M1 support?

**Comment by lordzsolt** [comment] 2021-03-31 09:48
Imagine needing 4 months to rebuild your project. Makes you wonder what AppsFlyer is doing under the hood...

**Comment by navartis** [comment] 2021-03-31 11:41
@lordzsolt Easy! 

Google also can't do this with their **GoogleMaps** and **GoogleSignIn** libraries 

Hm... May be **AppsFlyerFramework** and this Google libraries has cross dependencies... J

"Share, like, repost" please:
https://github.com/googlesamples/google-services/issues/495
https://github.com/googlesamples/google-services/issues/496

**Comment by lordzsolt** [comment] 2021-03-31 15:07
> @lordzsolt Easy!
> 
> Google also can't do this with their **GoogleMaps** and **GoogleSignIn** libraries
> 
> Hm... May be **AppsFlyerFramework** and this Google libraries has cross dependencies... J
> 
> "Share, like, repost" please:
> [googlesamples/google-services#495](https://github.com/googlesamples/google-services/issues/495)
> [googlesamples/google-services#496](https://github.com/googlesamples/google-services/issues/496)

Considering the amount of shady stuff Google is doing under the hood, I'm unsure if this point helps AppsFlyerFramework 😅 
(Specifically GoogleMobileAdsSDK, I don't know about these 2 you mentioned)


> We are very sorry your experience is less than perfect.
> 
> These days we run a QA cycle.
> Here is a branch: [AppsFlyerSDK/appsflyer-apple-sdk-qa@`dev`/m1/appsflyer-apple-sdk-qa.podspec#L64](https://github.com/AppsFlyerSDK/appsflyer-apple-sdk-qa/blob/dev/m1/appsflyer-apple-sdk-qa.podspec#L64)

That's good to hear. Hopefully by the time Apple releases M1 iPads, it'll be ready.

**Comment by AveTim** [comment] 2021-04-12 06:28
> We expect to release M1 support at the end of Feb.
Great scheduling and speed of updates for a multi-million dollar company.

**Comment by reddavis** [comment] 2021-04-12 13:13
Hey hey! 

I've found the m1 branch in the QA repo. Is the QA process documented anywhere? Imma trying to work out whether:

1. We can use the `xcframework` in the QA branch(understanding its possible to not be stable - but we'd like to submit bugs if we come across anything)
2. Now there is an M1 branch, what are the steps to get that into the main repo? I guess - roughly when should we expect that to be in the remain repo
3. If we find issues with with the QA builds, would you prefer us reporting issues in the QA repo or in this main one?

Thanks! 🙌

**Comment by atrinh0** [comment] 2021-04-28 13:12
> We are very sorry your experience is less than perfect.
> 
> These days we run a QA cycle.
> Here is a branch: https://github.com/AppsFlyerSDK/appsflyer-apple-sdk-qa/blob/dev/m1/appsflyer-apple-sdk-qa.podspec#L64

For what it's worth, this branch is working on my m1. 🥳

<img width="672" alt="Screenshot 2021-04-28 at 14 04 36" src="https://user-images.githubusercontent.com/16542463/116409306-a168eb80-a82b-11eb-9704-56a6f716630e.png">

**Comment by shakked** [comment] 2021-05-17 17:04
@atrinh0  How do you include that branch in cocoapods?

**Comment by jhascoet** [comment] 2021-05-18 06:33
> @atrinh0 How do you include that branch in cocoapods?

Simply put that in your podfile

`pod 'appsflyer-apple-sdk-qa', :git => 'git@github.com:AppsFlyerSDK/appsflyer-apple-sdk-qa.git', :branch => 'dev/m1'`

**Comment by andr-ggn** [comment] 2021-05-18 11:52
You can use `pod 'AppsFlyerFramework', '6.3.0'`
Also do not forget to update cocoapods `sudo gem install cocoapods`

**Comment by navartis** [comment] 2021-05-18 11:53
🎉👍🥳

**Comment by traktor74** [comment] 2021-05-18 13:32
also works fine with SPM from '6.3.0' version

**Closed** 2021-05-18 19:35 UTC

**Comment by matheusalano** [comment] 2021-06-20 02:25
Hey. Is it possible to update carthage json files to support xcframeworks? Thanks.
