### ISSUE TITLE
Not visionOS compatible

### ISSUE THREAD

**Issue by jrogccom** [AppsFlyerSDK/AppsFlyerFramework#289] opened 2024-05-08 22:03 UTC
# Report

Framework does not include a binary for visionOS

## SDK Version

`6.14.3`

## What did you do?

Added the (SPM) package to my visionOS project

## What did you expect to happen?

Successful compilation

## What happened instead?

Library does not compile for the visionOS platform

**Comment by amit-kremer93** [comment] 2024-06-16 10:57
duplicate of https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/261

**Closed by amit-kremer93** 2024-06-16 10:57 UTC
Labels: enhancement
