### ISSUE TITLE
Xcode 15.3 and App Store Connect Issue

### ISSUE THREAD

**Issue by gooson** [AppsFlyerSDK/AppsFlyerFramework#265] opened 2024-03-08 02:40 UTC
# Report

## SDK Version
6.13.1

## What did you do?
Xcode 15.3 - Archive my app and upload it to the App Store.

## What did you expect to happen?
Expect successful upload to App Store Connect

## What happened instead?
upload failed.
<img width="1634" alt="스크린샷 2024-03-08 오전 11 28 41" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/1947069/4595909b-a71c-450b-95c8-d56087d5d06b">

## Please provide any other relevant information.
Asset validation failed
Invalid Bundle. The bundle KREAM Inhouse.app/Frameworks/AppsFlyerLib.framework does not support the minimum OS Version specified in the Info.plist. (ID: d6f1120b-80ac-4987-93c9-f77662464369)

**Comment by alfredcc** [comment] 2024-03-08 06:35
+1

**Comment by sroyaura** [comment] 2024-03-08 19:12
This is blocking us from using the latest Xcode version to build and deploy.

**Comment by ersel95** [comment] 2024-03-09 11:57
Same issue here. Google and Facebook had the same issue. Solved with an update. Waiting for an update from your side too ASAP please.

**Comment by af-obodovskyi** [comment] 2024-03-11 10:31
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-1988098959

**Comment by umutturemen1496** [comment] 2024-03-11 13:24
I am using the master branch to get the most updated version as soon as possible. Nothing has changed since 3 days. Either Apple or you should fix this quickly. We cannot send an update.

![Screenshot 2024-03-11 at 14 23 44](https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/83616491/3ea393d7-ecfb-4c7e-8c79-7f2f49d37abe)

**Comment by krotoff** [comment] 2024-03-11 14:01
+1 here, waiting for the update

**Comment by alxrguz** [comment] 2024-03-11 15:37
+1

**Comment by vladimirDarksy** [comment] 2024-03-11 17:27
+1

**Comment by dvdjmnz** [comment] 2024-03-11 17:36
+1

**Comment by via-guy** [comment] 2024-03-11 23:05
+1

**Comment by KimHyunMin1751** [comment] 2024-03-13 01:32
+1

**Comment by mwirtz112** [comment] 2024-03-14 03:04
+1

**Comment by af-obodovskyi** [comment] 2024-03-14 10:53
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-1997163247

**Comment by sefaaycicek** [comment] 2024-03-14 19:09
You can use cocoapods instead of spm until the problem is solved.

**Comment by TizianoCoroneo** [comment] 2024-03-15 09:55
> You can use cocoapods instead of spm until the problem is solved.

We removed Cocoapods from our project years ago, this is not an option

**Comment by TizianoCoroneo** [comment] 2024-03-15 10:03
@af-obodovskyi 

The metadata inside the .xcframework file that you fetch from the `Package.swift` file indicates that the build has been made with Xcode 12.5.1 from 2021. To use a version of Xcode 3 years old is unacceptable for a framework vendor; we will be removing AppsFlyer for the time being. We'd be happy to add it back once you figure out these packaging issues.

![Screenshot 2024-03-15 at 11 02 05](https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/15340382/680cd42e-9285-4c6c-a75a-b2ec85b5081c)

**Comment by Hartistic** [comment] 2024-03-15 14:08
same here, can we get this fixed?

**Comment by johantorstensson** [comment] 2024-03-19 12:35
This is ridiculous! I don't want to go backwards to cocoapods.. plz!

**Comment by sauravexodus** [comment] 2024-03-19 18:29
Fix this guys!

**Comment by mwirtz112** [comment] 2024-03-19 19:48
Any Updates? It's been 2 weeks here?

**Comment by jamesrogers93** [comment] 2024-03-19 19:52
Xcode 15.3 causes issues for me. I worked around by simply reinstalling Xcode 15.2

**Comment by IdoMDigiBank** [comment] 2024-03-20 06:49
Any Updates?

**Comment by Hartistic** [comment] 2024-03-20 13:15
I would like to emphasize our growing concern regarding the current compatibility issues with the Xcode 15.3 compiler on Xcode Cloud, which has significantly impacted our development workflow. The decision to integrate a third-party framework into our projects is heavily influenced by the level of responsiveness and support offered. Given the subscription cost associated with utilizing your framework, our expectations align with receiving prompt and prioritized support.

We understand the complexities involved in addressing such issues; however, the proposed timeline for a resolution by March 25th raises **substantial concerns** within our team. The delay is prompting us to **reevaluate our continued use** of your product.

We appreciate the hard work and dedication of your development team. In light of our commitment to using AppsFlyer, we kindly urge you to consider allocating additional resources to expedite the resolution of this compatibility issue. A more immediate fix would greatly assist us in maintaining our development schedule and reinforce our confidence in your framework as a reliable component of our software stack.

**Comment by FabianBartels** [comment] 2024-03-20 15:24
I fixed it by downgrading to Xcode version 15.2.
Hint: This is not only happening to AppsFlyer but also to Facebook and i am sure others also suffer from this.

I hope it helped you :)

**Comment by TizianoCoroneo** [comment] 2024-03-22 21:29
I found a comment in a similar thread for the Facebook SDK, here's a possible workaround for the moment:

> From the organizer -> open the archived by finder -> open the content of the app -> frameworks -> framework which has the issue -> info.plist
> `MinimumOsVersion = 15.0.0` [or your min OS version]

https://github.com/facebook/facebook-ios-sdk/issues/2353#issuecomment-2011309022

**Comment by mwirtz112** [comment] 2024-03-23 21:14
+1 to Hartistic, This is becoming unreasonable. We will be transferring to another service by the end of this week if the issue is not solved.

**Comment by johantorstensson** [comment] 2024-03-25 10:17
Nevermind, I just got news we cancelled this service. Good luck y'all ;)

**Comment by af-obodovskyi** [comment] 2024-03-26 14:30
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-2020589166

**Closed by af-obodovskyi** 2024-03-26 14:30 UTC

**Comment by kirandwarkan** [comment] 2024-03-26 20:31
I updated to version 6.13.2 and still got a validation error uploading to TestFlight. This does not appear to have been fixed.

**Comment by ob1vansk1y** [comment] 2024-03-26 21:19
@kirandwarkan please, use spm repositories in the documentation to the AppsFlyerFramework for static, dynamic and strict dependencies respectively. Clear SPM cache and try again, it fixes the issue

**Comment by IdoMDigiBank** [comment] 2024-03-27 12:09
I also update to version 6.13.2 and also did SPM clear cache, but still got a validation error uploading to TestFlight.

**Comment by alpha-moisol** [comment] 2024-03-29 08:32
I managed to upload my build, but got this warning letter from AppStoreConnect
```ITMS-90747: Architecture incompatible with MinimumOSVersion. The app bundle at '***.app/Frameworks/AppsFlyerLib.framework' specifies a MinimumOSVersion of '100.0' but contains a 32-bit architecture that is unsupported on iOS 12 and later.```
